services:
  # Backend da aplicação (Flask)
  server:
    build: ./Server
    container_name: flask_server
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      FLASK_ENV: "production"
      DATABASE_HOST: "${DATABASE_HOST}"
      DATABASE_PORT: "3306"
      DATABASE_USER: "${DATABASE_USER}"
      DATABASE_PASSWORD: "${DATABASE_PASSWORD}"
      DATABASE_NAME: "${DATABASE_NAME}"
      MEMCACHED_HOST: "${MEMCACHED_HOST}"
      MEMCACHED_PORT: "${MEMCACHED_PORT}"
    env_file:
      - .env
    depends_on:
      mariadb:
        condition: service_healthy
      memcached:
        condition: service_started
    networks:
      - app-network
    restart: on-failure:3

  # Banco de dados de cache
  memcached:
    image: memcached:alpine
    container_name: cache_memcached
    ports:
      - "${CACHE_PORT}:${CACHE_PORT}"
    networks:
      - app-network
    restart: unless-stopped

# Banco de dados relacional
  mariadb:
    image: mariadb:latest
    container_name: db_mariadb
    environment:
      MARIADB_ROOT_PASSWORD: "${DATABASE_PASSWORD}"
      MARIADB_DATABASE: "${DATABASE_NAME}"
    env_file:
      - .env
    ports:
      - "3307:3306"
    volumes:
      # Mantemos o volume nomeado para não perder os dados do banco
      - ./mariadb_data:/var/lib/mysql:z
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  # Explicitamos que o mariadb_data usa o driver padrão (local) do Docker
  mariadb_data:
    driver: local

networks:
  app-network:
    driver: bridge
